import { useState } from 'react';
import { BarChart3, Download, Filter, FileText, PieChart, TrendingUp, X } from 'lucide-react';

export default function Reports() {
  const [reports, setReports] = useState([
    { id: 'REP-2023-11', type: 'Gateway P&L', generated: '2 hours ago', size: '2.4 MB' },
    { id: 'REP-2023-11-TAX', type: 'Global Tax Liability', generated: '1 day ago', size: '1.1 MB' },
    { id: 'REP-2023-10', type: 'Gateway P&L', generated: '1 month ago', size: '2.3 MB' },
    { id: 'REP-2023-Q3', type: 'Quarterly Volume', generated: '3 months ago', size: '8.4 MB' },
  ]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isFilterActive, setIsFilterActive] = useState(false);

  const handleGenerateReport = (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const type = formData.get('type');
    
    const newReport = {
      id: `REP-${new Date().getFullYear()}-${Math.floor(Math.random() * 1000)}`,
      type: type,
      generated: 'Just now',
      size: 'Generating...'
    };
    
    setReports([newReport, ...reports]);
    setIsModalOpen(false);
    
    // Simulate size update after "generation"
    setTimeout(() => {
      setReports(prev => prev.map(r => r.id === newReport.id ? { ...r, size: (Math.random() * 5 + 1).toFixed(1) + ' MB' } : r));
    }, 2000);
  };

  const handleDownload = (reportId) => {
    const content = `Mock PDF Report Content for ${reportId}\n\nGenerated by PGX Gateway System.\nDate: ${new Date().toLocaleString()}`;
    const blob = new Blob([content], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportId}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-in fade-in zoom-in-95 duration-500">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-black text-white flex items-center gap-3">
            <BarChart3 className="w-8 h-8 text-[#7C3AED]" /> System Reports & Analytics
          </h1>
          <p className="text-gray-400 mt-1">Generate and download master P&L, volume, and tax reports.</p>
        </div>
        <div className="flex gap-2">
          <button onClick={() => setIsFilterActive(!isFilterActive)} className={`${isFilterActive ? 'bg-[#7C3AED]/20 text-[#7C3AED] border-[#7C3AED]/50' : 'bg-white/5 hover:bg-white/10 text-white border-white/10'} px-4 py-2 rounded-xl text-sm font-bold flex items-center gap-2 border transition-all`}>
            <Filter className="w-4 h-4" /> Filter
          </button>
          <button onClick={() => setIsModalOpen(true)} className="bg-[#7C3AED] hover:bg-[#6D28D9] text-white px-4 py-2 rounded-xl text-sm font-bold shadow-[0_0_15px_rgba(124,58,237,0.3)] flex items-center gap-2 transition-all">
            <FileText className="w-4 h-4" /> Generate New
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        <div className="bg-[#13131A] border border-white/5 rounded-2xl p-6 shadow-xl flex items-center justify-between">
           <div>
             <p className="text-gray-400 text-xs font-bold uppercase mb-1">Total Processed (YTD)</p>
             <h3 className="text-3xl font-black text-white">$1.24B</h3>
             <span className="text-green-500 text-xs font-bold flex items-center gap-1 mt-1"><TrendingUp className="w-3 h-3"/> +14.5% vs Last Year</span>
           </div>
           <PieChart className="w-12 h-12 text-[#7C3AED] opacity-50" />
        </div>
      </div>

      <div className="bg-[#13131A] border border-white/5 rounded-2xl shadow-xl overflow-hidden">
        <div className="p-4 border-b border-white/5 flex gap-4">
          <h3 className="text-lg font-bold text-white">Generated Reports</h3>
        </div>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="text-gray-500 text-xs font-bold uppercase border-b border-white/5 bg-white/[0.02]">
              <th className="p-4">Report ID</th>
              <th className="p-4">Type</th>
              <th className="p-4">Generated</th>
              <th className="p-4">Size</th>
              <th className="p-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5 text-sm">
            {reports.map((r, i) => (
              <tr key={i} className="hover:bg-white/[0.02]">
                <td className="p-4 font-mono font-bold text-gray-400">{r.id}</td>
                <td className="p-4 font-bold text-white">{r.type}</td>
                <td className="p-4 text-gray-400">{r.generated}</td>
                <td className="p-4 text-gray-500 text-xs">{r.size}</td>
                <td className="p-4 flex justify-end gap-2">
                  <button onClick={() => handleDownload(r.id)} className="p-2 text-cyan-500 bg-cyan-500/10 hover:bg-cyan-500/20 rounded-lg flex items-center gap-2 text-xs font-bold transition-colors">
                    <Download className="w-4 h-4" /> Download PDF
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-[#13131A] border border-white/10 rounded-2xl shadow-2xl w-full max-w-md animate-in zoom-in-95 duration-200">
            <div className="flex justify-between items-center p-6 border-b border-white/5">
              <h2 className="text-xl font-bold text-white">Generate New Report</h2>
              <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-white transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>
            <form onSubmit={handleGenerateReport} className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-bold text-gray-400 mb-1">Report Type</label>
                <select name="type" className="w-full bg-black/50 border border-white/10 rounded-lg px-4 py-2 text-white focus:border-[#7C3AED] outline-none appearance-none">
                  <option>Gateway P&L</option>
                  <option>Global Tax Liability</option>
                  <option>Quarterly Volume</option>
                  <option>Merchant Risk Analysis</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-bold text-gray-400 mb-1">Date Range</label>
                <select name="range" className="w-full bg-black/50 border border-white/10 rounded-lg px-4 py-2 text-white focus:border-[#7C3AED] outline-none appearance-none">
                  <option>Last 7 Days</option>
                  <option>Last 30 Days</option>
                  <option>This Quarter</option>
                  <option>Year to Date</option>
                </select>
              </div>
              
              <div className="pt-4 flex gap-3">
                <button type="button" onClick={() => setIsModalOpen(false)} className="flex-1 bg-white/5 hover:bg-white/10 text-white py-2 rounded-lg font-bold transition-colors">
                  Cancel
                </button>
                <button type="submit" className="flex-1 bg-[#7C3AED] hover:bg-[#6D28D9] text-white py-2 rounded-lg font-bold shadow-[0_0_15px_rgba(124,58,237,0.3)] transition-colors">
                  Generate Report
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
