import { useState, useEffect } from 'react';
import { BarChart3, Download, Filter, FileText, PieChart, TrendingUp, X, Loader2 } from 'lucide-react';
import apiClient from '../../../utils/apiClient';

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isFilterActive, setIsFilterActive] = useState(false);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const res = await apiClient.get('/admin/reports/system');
      if (res.success && res.data) {
        setReports(res.data);
      }
    } catch (error) {
      console.error('Failed to fetch reports', error);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateReport = async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const payload = {
      type: formData.get('type'),
      range: formData.get('range')
    };
    
    try {
      setGenerating(true);
      await apiClient.post('/admin/reports/system', payload);
      await fetchReports();
      setIsModalOpen(false);
    } catch (error) {
      console.error('Failed to generate report', error);
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = (reportId, fileUrl) => {
    // Always generate a blob for demonstration since the fileUrl is a mock url
    const content = `Report Content for ${reportId}\n\nGenerated by PGX Gateway System.\nDate: ${new Date().toLocaleString()}\nSource URL: ${fileUrl || 'N/A'}`;
    const blob = new Blob([content], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportId}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const timeAgo = (date) => {
    if (!date) return 'Never';
    const seconds = Math.floor((new Date() - new Date(date)) / 1000);
    if (seconds < 60) return `${seconds} secs ago`;
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) return `${minutes} mins ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours} hrs ago`;
    const days = Math.floor(hours / 24);
    if (days < 30) return `${days} days ago`;
    const months = Math.floor(days / 30);
    return `${months} months ago`;
  };

  return (
    <div className="space-y-6 animate-in fade-in zoom-in-95 duration-500">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-black text-white flex items-center gap-3">
            <BarChart3 className="w-8 h-8 text-[#7C3AED]" /> System Reports & Analytics
          </h1>
          <p className="text-gray-400 mt-1">Generate and download master P&L, volume, and tax reports.</p>
        </div>
        <div className="flex gap-2">
          <button onClick={() => setIsFilterActive(!isFilterActive)} className={`${isFilterActive ? 'bg-[#7C3AED]/20 text-[#7C3AED] border-[#7C3AED]/50' : 'bg-white/5 hover:bg-white/10 text-white border-white/10'} px-4 py-2 rounded-xl text-sm font-bold flex items-center gap-2 border transition-all`}>
            <Filter className="w-4 h-4" /> Filter
          </button>
          <button onClick={() => setIsModalOpen(true)} className="bg-[#7C3AED] hover:bg-[#6D28D9] text-white px-4 py-2 rounded-xl text-sm font-bold shadow-[0_0_15px_rgba(124,58,237,0.3)] flex items-center gap-2 transition-all">
            <FileText className="w-4 h-4" /> Generate New
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        <div className="bg-[#13131A] border border-white/5 rounded-2xl p-6 shadow-xl flex items-center justify-between">
           <div>
             <p className="text-gray-400 text-xs font-bold uppercase mb-1">Total Processed (YTD)</p>
             <h3 className="text-3xl font-black text-white">$1.24B</h3>
             <span className="text-green-500 text-xs font-bold flex items-center gap-1 mt-1"><TrendingUp className="w-3 h-3"/> +14.5% vs Last Year</span>
           </div>
           <PieChart className="w-12 h-12 text-[#7C3AED] opacity-50" />
        </div>
      </div>

      <div className="bg-[#13131A] border border-white/5 rounded-2xl shadow-xl overflow-hidden">
        <div className="p-4 border-b border-white/5 flex gap-4">
          <h3 className="text-lg font-bold text-white">Generated Reports</h3>
        </div>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="text-gray-500 text-xs font-bold uppercase border-b border-white/5 bg-white/[0.02]">
              <th className="p-4">Report ID</th>
              <th className="p-4">Type</th>
              <th className="p-4">Generated</th>
              <th className="p-4">Size</th>
              <th className="p-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5 text-sm">
            {loading ? (
              <tr>
                <td colSpan="5" className="p-8 text-center text-gray-400">
                  <Loader2 className="w-6 h-6 animate-spin mx-auto text-[#7C3AED] mb-2" />
                  Loading reports...
                </td>
              </tr>
            ) : reports.length === 0 ? (
              <tr>
                <td colSpan="5" className="p-8 text-center text-gray-500">
                  No generated reports found. Click 'Generate New' to create one.
                </td>
              </tr>
            ) : (
              reports.map((r) => (
                <tr key={r.reportId} className="hover:bg-white/[0.02]">
                  <td className="p-4 font-mono font-bold text-gray-400">{r.reportId.substring(0, 18)}...</td>
                  <td className="p-4 font-bold text-white">{r.reportType}</td>
                  <td className="p-4 text-gray-400">{timeAgo(r.generatedAt)}</td>
                  <td className="p-4 text-gray-500 text-xs">{r.fileSize}</td>
                  <td className="p-4 flex justify-end gap-2">
                    <button onClick={() => handleDownload(r.reportId, r.fileUrl)} className="p-2 text-cyan-500 bg-cyan-500/10 hover:bg-cyan-500/20 rounded-lg flex items-center gap-2 text-xs font-bold transition-colors">
                      <Download className="w-4 h-4" /> Download PDF
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-[#13131A] border border-white/10 rounded-2xl shadow-2xl w-full max-w-md animate-in zoom-in-95 duration-200">
            <div className="flex justify-between items-center p-6 border-b border-white/5">
              <h2 className="text-xl font-bold text-white">Generate New Report</h2>
              <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-white transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>
            <form onSubmit={handleGenerateReport} className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-bold text-gray-400 mb-1">Report Type</label>
                <select name="type" className="w-full bg-black/50 border border-white/10 rounded-lg px-4 py-2 text-white focus:border-[#7C3AED] outline-none appearance-none">
                  <option>Gateway P&L</option>
                  <option>Global Tax Liability</option>
                  <option>Quarterly Volume</option>
                  <option>Merchant Risk Analysis</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-bold text-gray-400 mb-1">Date Range</label>
                <select name="range" className="w-full bg-black/50 border border-white/10 rounded-lg px-4 py-2 text-white focus:border-[#7C3AED] outline-none appearance-none">
                  <option>Last 7 Days</option>
                  <option>Last 30 Days</option>
                  <option>This Quarter</option>
                  <option>Year to Date</option>
                </select>
              </div>
              
              <div className="pt-4 flex gap-3">
                <button type="button" onClick={() => setIsModalOpen(false)} className="flex-1 bg-white/5 hover:bg-white/10 text-white py-2 rounded-lg font-bold transition-colors">
                  Cancel
                </button>
                <button type="submit" disabled={generating} className="flex-1 flex justify-center items-center gap-2 bg-[#7C3AED] hover:bg-[#6D28D9] text-white py-2 rounded-lg font-bold shadow-[0_0_15px_rgba(124,58,237,0.3)] transition-colors disabled:opacity-50">
                  {generating ? <Loader2 className="w-4 h-4 animate-spin"/> : null}
                  {generating ? 'Generating...' : 'Generate Report'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
